# 一、ndarray
## 1.ndarray的特性
### 多维性

In [2]:
import numpy as np

In [2]:
arr = np.array(5)  # 创建0维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim)   # 数组的维度number of dimensions

5
arr的维度： 0


In [3]:
arr = np.array([1, 2, 3])  # 创建1维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim)   # 数组的维度number of dimensions

[1 2 3]
arr的维度： 1


In [4]:
arr = np.array([ [1, 2, 3], [4, 5, 6]])  # 创建2维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim)   # 数组的维度number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度： 2


### 同质性

In [ ]:
arr = np.array([1, 'hello'])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

In [ ]:
arr = np.array([1, 2.5])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

## 2.ndarray的属性

In [ ]:
arr = np.array(1)
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('元素的转置', arr.T)

In [ ]:
arr = np.array([1, 2.5, 3])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('元素的转置', arr.T)

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的转置', arr.T)

## 3.ndarray的创建

In [ ]:
# 基础的创建方法
list1 = [4, 5, 6]
arr = np.array(list1,dtype=np.float64)
print(arr.ndim)  # 属性
print(arr)

In [ ]:
# copy
arr1 = np.copy(arr)  # 元素跟原始的数组相同，但是不是一个数组了
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

In [ ]:
# 预定义形状
# 全0  全1  未初始化  固定值
# 全0
arr = np.zeros((2,3),dtype=int)
print(arr)
print(arr.dtype)

In [ ]:
arr = np.zeros((200,),dtype=int)
print(arr)

In [ ]:
# 全1
arr = np.ones((5,8),dtype=int)
print(arr)

In [ ]:
# 未初始化
arr = np.empty((2,3))
print(arr)

In [ ]:
arr = np.empty((4, 2))
print(arr)

In [ ]:
arr = np.full((3,4),2025)
print(arr)

In [ ]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr,2026)
print(arr1)

In [ ]:
# 等差数列 2 4 6 8 10
arr = np.arange(1, 51, 1) # start,end,step(步长）
print(arr)

In [ ]:
# 等间隔数列
arr = np.linspace(0,100,5)
print(arr)

In [ ]:
arr = np.linspace(0,100,5,dtype=int)
print(arr)
arr = np.arange(0,101, 25)
print(arr)

In [ ]:
# 对数间隔数列
arr = np.logspace(0,4,3,base=2)
print(arr)

In [ ]:
arr = np.linspace(0,4,3)
print(arr)

In [ ]:
arr = np.logspace(0,4,3)
print(arr)

In [ ]:
# 特殊矩阵
# 单位矩阵：主对角线上的数字为1，其他的数字为0
arr = np.eye(3,4,dtype=int)
print(arr)


In [ ]:
# 对角矩阵：主对角线上非零的0，其他的数字为0
arr = np.diag([5,1,2,3])
print(arr)

In [ ]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2,3)
print(arr)

In [12]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3, 6,(2,3))
print(arr)

[[3.13294439 3.2955133  3.57839635]
 [4.24193096 3.10484865 5.17452865]]


In [13]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 30,(2,3))
print(arr)

[[12 27  4]
 [ 7  9 26]]


In [ ]:
# 生成随机数列（正态分布）（-3到3之间）
# 两边小，中间大
arr = np.random.randn(2,3)
print(arr)

In [ ]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,(2,5))
print(arr)

In [ ]:
arr = np.array([1,2,3],dtype='i8')
print(arr)

4. ndarray的数据类型

布尔类型 bool

整数类型  int  uint

浮点数   float

复数  complex

In [ ]:
arr = np.array([1,0,127,0],dtype= np.int8)
print(arr)

5. 索引与切片

In [ ]:
# 一维数组的索引与切片
arr = np.random.randint(1,100,20)
print(arr)

In [ ]:
print(arr[10])
print(arr[:]) # 获取全部的数据
print(arr[2:5])  # start:end+1 左包右不包
print(arr[slice(2,15,3)])  #start,end,step
print(arr[ (arr>10)  & (arr<70) ]) # 布尔索引

In [ ]:
# 二维数组的索引与切片
arr = np.random.randint(1,100,(4,8))
print(arr)

In [ ]:
print(arr[1,3])  # 索引
print(arr[ 1,2:5])
print(arr[2][  arr[2] > 50 ])
print( arr[:,3] )

5. ndarray的运算

In [ ]:
# 算术运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

In [ ]:
c = [1, 2, 3]
d = [4, 5, 6]
for i in range(len(c)):
    d[i] = d[i]+c[i]
print(d)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

In [ ]:
# 数组与标量之间的算术运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a + 3)
print(a * 3)

In [6]:
# 广播机制: 1.获取形状 2.是否可广播
# 同一维度：相同、1
a = np.array([1,2,3]) #1*3
b = np.array([[4],[5],[6]])  #3*1
print(b - a )
'''a
 1 2 3
 1 2 3
 1 2 3
 b
 4 4 4
 5 5 5
 6 6 6
'''

[[3 2 1]
 [4 3 2]
 [5 4 3]]


'a\n 1 2 3\n 1 2 3\n 1 2 3\n b\n 4 4 4\n 5 5 5\n 6 6 6\n'

In [ ]:
a = np.array([1,2,3]) #1*3
b = np.array([4,5])  #1*2
print(b - a )

In [ ]:
# 矩阵运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a @ b)

In [ ]:
'''a
1 2 3
4 5 6
7 8 9
b
4 5 6
7 8 9

1 2 3'''


# 2.3 numpy中的常用函数
## 1. 基本数学函数

In [5]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [ ]:
# 计算指数  e^x  = y
print(np.exp(1))

In [ ]:
# 计算自然对数  ln y = x
print(np.log(2.71))

In [ ]:
# 计算正弦值、余弦值
print(np.sin(np.pi/2))
print(np.cos(np.pi))

In [ ]:
# 计算绝对值
arr = np.array([-1, 1, 2, -3])
print(np.abs(arr))

In [ ]:
# 计算a的b次幂
print(np.power(arr,3))

In [ ]:
# 四舍五入
print(np.round([3.2, 4.5, 8.1, 9.6]))

In [ ]:
# 向上取整，向下取整
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr))
print(np.floor(arr))

In [ ]:
# 检测缺失值NaN
np.isnan([1, 2, np.nan, 3])

2.统计函数

求和、计算平均值、计算中位数、标准差、方差

查找最大值、最小值

计算分位数、累积和、累积差


In [3]:
arr = np.random.randint(1,200,8)
print(arr)

[183  51 188  43 175  32  41 170]


In [4]:
# 求和
print(np.sum([1,2,3]))

6


In [ ]:
# 计算平均值
print(np.mean(arr))

In [11]:
# 计算中位数
# 奇数：排序后中间的数值
# 偶数：中间的两个数的平均值
# print(np.median([4,1,2]))
print(np.median([[2,7,1,5,2,1,6,5,4,100],[4,3,2,1,5,6,3,4,2,100]]))

4.0


In [ ]:
# 计算标准差、方差
# 1,2,3 的平均值 2
# ((1-2)^2 + (2-2)^2 + (3-2)^2 )/ 3 = 0.666
arr1 = np.array([1,2,1,2,1,1,1,2])
arr2 = np.array([1,0,3,0,0,0,4,3])
print(np.mean(arr1))
print(np.mean(arr2))
print(np.var(arr1))
print(np.var(arr2))

In [ ]:
# 计算最大值、最小值
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))

In [ ]:
# 分位数
# 中位数
# __________________
# 1     2    3     4
# 1       2        3
print(np.median([1,2,3]))
print(np.median([1,2,3,4]))
np.random.seed(0)
arr = np.random.randint(0,100,4)
print(arr)
# __________________
# 44   47   64   67
# (47+64)/2
print(np.median(arr))
print(np.percentile(arr,80))
# 0.25*3=0.75
# (47-44)*0.75=2.25 + 44 = 46.25
# 3*0.8 = 2.4
# (67-64)*0.4 = 1.2 + 64 = 65.2

In [ ]:
# 累积和、累积积
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

In [ ]:
# 创建嵌套JSON结构的数据
import numpy as np
products = {
    "products": [
        {
            "id": f"P{i}",
            "name": f"Product {i}",
            "category": np.random.choice(["Electronics", "Clothing", "Home", "Food"]),
            "price": round(np.random.uniform(5, 200), 2),
            "in_stock": np.random.choice([True, False]),
            "specs": {
                "weight": round(np.random.uniform(0.1, 5), 2),
                "dimensions": {
                    "length": np.random.randint(5, 50),
                    "width": np.random.randint(5, 30),
                    "height": np.random.randint(5, 20)
                }
            }
        } for i in range(1, 21)
    ]
}

# 保存为JSON
import json
with open('data/products.json', 'w') as f:
    json.dump(products, f, indent=2)